# Generated by Django 4.1.7 on 2023-02-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Task name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('date', models.DateField()),
            ],
        ),
    ]
