# Generated by Django 4.1.7 on 2023-02-21 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Завдання', 'verbose_name_plural': 'Завдання'},
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2023, 2, 21)),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
