# Generated by Django 4.1.7 on 2023-02-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_end',
            field=models.DateField(null=True),
        ),
    ]
